name: Danger CI

on: [pull_request, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger main check
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: |
          npm install --save-dev @babel/plugin-transform-flow-strip-types
      - name: Danger
        uses: danger/danger-js@11.2.8
        with:
          args: "--dangerfile ./tools/danger/dangerfile.js"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          # Fallback for forks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
